services:
  - type: web
    name: footprint
    runtime: python
    plan: free
    rootDir: files
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: footprint-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.0"

databases:
  - name: footprint-db
    plan: free
    databaseName: footprint
    user: footprint_user
