databases:
  - name: footprint-db
    databaseName: footprint
    user: footprint
    plan: free

services:
  - type: web
    name: footprint
    runtime: python
    plan: free
    buildCommand: pip install -r files/requirements.txt
    startCommand: cd files && gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: footprint-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
